export { Home } from './Home'
export { Shop } from './Shop'
export { Blog } from './Blog'
export { CartPage } from './CartPage'
export { Checkout } from './Checkout'
export { Product } from './Product'
export { Docs } from './Docs'
