export { Header } from './Header'
export { Navbar } from './Navbar'
export { Footer } from '../shared/components/common/Footer'
export { MainSlider } from './MainSlider'
export { OfferLinks } from './OfferLinks'
export { OurBlog } from './OurBlog'
export { Sale } from './Sale'
export { Mostview } from './Mostview'
export { Offers } from './Offers'
export { FeaturedProducts } from './FeaturedProducts'
export { Copyright } from './Copyright'
export { ShopComp } from './ShopComp'
export { ProductDetails } from '../modules/ProductDetail/ProductDetails'
export { RelatedProducts } from './RelatedProducts'

