export { Header } from './Header'
export { Footer } from './Footer'
export { MainSlider } from './MainSlider'
export { OfferLinks } from './OfferLinks'
export { OurBlog }  from './OurBlog'
export { Sale } from './Sale'
export { Mostview } from './Mostview'
