export const siteMap = {
	pages: [
		{ page: 'Home', url: '/' },
		{ page: 'Affiliate', url: '/affiliate', badge: 'Coming soon' },
		{ page: 'Delivery', url: '/delivery', badge: 'Coming soon' },
		{ page: 'Contact us', url: '/contact-us' },
		{ page: 'Categories', url: '/categories' },
		{ page: 'Privacy policy', url: '/privacy-policy' },
		{ page: 'Compare', url: '/compare' },
		{ page: 'Wishlist', url: '/wishlist' },
		{ page: 'Subscriptions', url: '/profile/subscriptions' },
		{ page: 'Verify email', url: '/verify-email' },
		{ page: 'Brands', url: '/brands' },
		{ page: 'Specials', url: '/specials', badge: 'Coming soon' },
		{ page: 'Blog', url: '/blog' },
		{ page: 'Terms & conditions', url: '/terms-conditions' },
		{ page: 'Cart', url: '/cart' },
		{ page: 'Change email', url: '/change-email' },
		{ page: 'Login', url: '/login' },
		{ page: 'Gift cards', url: '/gift-cards', badge: 'Coming soon' },
		{ page: 'Returns', url: '/returns', badge: 'Coming soon' },
		{ page: 'Roadmap', url: '/road-map' },
		{ page: 'Profile', url: '/profile/profile-details' },
		{ page: 'About us', url: '/about-us' },
		{ page: 'Frequently Questions', url: '/faq' },
		{ page: 'Shop', url: '/shop' },
		{ page: 'Checkout', url: '/checkout' },
		{ page: 'Order history', url: '/order-history', badge: 'Coming soon' },
		{ page: 'Change password', url: '/change-password' },
		{ page: 'Reset password', url: '/reset-password' },
		{ page: 'Register', url: '/register' },
	],
}
